# Modify object file to directory
OBJ = ../../build/obj/c-log.o

# Module source files
SRC  = src/LogBook.cpp
SRC += src/Logger.cpp
SRC += src/LogSystem.cpp

$(OBJ) : 
	g++ --std=c++20 -r $(SRC) -o $(OBJ)
